Blog/project_blog/accounts/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path(
        "login/",
        auth_view.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_view.LogoutView.as_view(), name="logout",),
]

Blog/project_blog/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
]

Blog/project_blog/project_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/project_blog/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default="default.jpg", upload_to="profile_pics")

	def __str__(self):
		return f'{self.user.username} Profile'

Blog/project_blog/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone



class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
    	return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(default="default.jpg")
    content = models.TextField()
    create_on = models.DateTimeField(auto_now_add=True)
    date_posted = models.DateTimeField(default=timezone.now)
    modified_on = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
    	return self.title

Blog/project_blog/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

Blog/project_blog/accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


from .forms import UserRegisterationForm


def register(request):
    if request.method == "POST":
        form = UserRegisterationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account created for {username}")
            return redirect("blog:index")
    else:
        form = UserRegisterationForm()
    return render(request, "accounts/register.html", {"form": form})


@login_required
def profile(request):
    return render(request, "accounts/profile.html")

Blog/project_blog/blog/views.py
from django.shortcuts import render
from .models import Post

# home page 
def index(request):
    posts = Post.objects.all()
    return render(request, "blog/index.html", {"posts": posts})

Blog/project_blog/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
    <h3>Login Here</h3>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form | crispy }}
        </fieldset>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <dib class="border-top pt-3">
        <small class="text-muted">
            <p>Need An Account? <a href="{%url 'accounts:register' %}">Sign Up</a></p>
        </small>
    </dib>
{% endblock content %}

Blog/project_blog/accounts/templates/accounts/logout.html
<h1>You have been logged out</h1>
<a href="{% url 'accounts:login' %}">Login again</a>

Blog/project_blog/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Profile{% endblock title %}
{% block content %}
	<h1>Profile Page</h1>
	<img src="{{ user.profile.image.url }}" width="20%">
	<p>Username: {{ user.username }}</p>
	<p>Email: {{ user.email }}</p>

{% endblock content %}

Blog/project_blog/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Register User{% endblock title %}
{% block content %}
    <h1>Fill the form to register</h1>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form | crispy }}
        </fieldset>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <dib class="border-top pt-3">
        <small class="text-muted">
            <p>Already have an account <a href="{%url 'accounts:login' %}">Login</a></p>
        </small>
    </dib>
{% endblock content %}

Blog/project_blog/blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">
    <title>{% block title %}BASE{% endblock title %}</title>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active ">
            <a class="nav-link " href="{% url 'blog:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          {% else %}    
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
    {% comment %} if any message exist it will be displayed {% endcomment %}
    {% if messages %}
        {% for message in messages %}
            <div class="alter alert-{{message.tags}}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Blog/project_blog/blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog Home{% endblock title %}
{% block content %}


  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Page Heading
          <small>Secondary Text</small>
        </h1>

        {% for post in posts %}
          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text">{{ post.content }}</p>
              <a href="#" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Post on {{ post.date_posted }}
              <a href="#">{{ post.author }}</a>
            </div>
          </div>
        {% endfor %}

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>


{% endblock content %}